/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Cities: () => import('#controllers/cities_controller'),
  Products: () => import('#controllers/products_controller'),
  SellingPlaces: () => import('#controllers/selling_places_controller'),
  Events: () => import('#controllers/events_controller'),
  Subscribers: () => import('#controllers/subscribers_controller'),
  Announcements: () => import('#controllers/announcements_controller'),
  Settings: () => import('#controllers/settings_controller'),
}
