/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Announcements: () => import('#controllers/announcements_controller'),
  Cities: () => import('#controllers/cities_controller'),
  ContactPeople: () => import('#controllers/contact_people_controller'),
  DateProductStocks: () => import('#controllers/date_product_stocks_controller'),
  Dates: () => import('#controllers/dates_controller'),
  DistributionDates: () => import('#controllers/distribution_dates_controller'),
  Events: () => import('#controllers/events_controller'),
  Lieux: () => import('#controllers/lieux_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  ProductImages: () => import('#controllers/product_images_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reservations: () => import('#controllers/reservations_controller'),
  SellingPlaces: () => import('#controllers/selling_places_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Subscribers: () => import('#controllers/subscribers_controller'),
}
