FROM node:20-alpine AS builder
WORKDIR /app
COPY front/package*.json ./
RUN npm ci
COPY front/ .
RUN npx ng build --configuration=production

FROM nginx:alpine
COPY --from=builder /app/dist/front/browser /usr/share/nginx/html
COPY docker/front/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
