/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnnouncementSchema extends BaseModel {
  static $columns = ['createdAt', 'eventDate', 'id', 'isActive', 'location', 'showLimitedQuantities', 'title', 'updatedAt'] as const
  $columns = AnnouncementSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventDate: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare location: string
  @column()
  declare showLimitedQuantities: boolean | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CitySchema extends BaseModel {
  static $columns = ['address', 'color', 'createdAt', 'id', 'name', 'notes', 'type', 'updatedAt'] as const
  $columns = CitySchema.$columns
  @column()
  declare address: string | null
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DateSchema extends BaseModel {
  static $columns = ['capacity', 'createdAt', 'date', 'id', 'lieuId', 'notes', 'time', 'updatedAt'] as const
  $columns = DateSchema.$columns
  @column()
  declare capacity: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lieuId: number | null
  @column()
  declare notes: string | null
  @column()
  declare time: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DistributionDateSchema extends BaseModel {
  static $columns = ['capacity', 'cityId', 'createdAt', 'date', 'id', 'notes', 'time', 'updatedAt'] as const
  $columns = DistributionDateSchema.$columns
  @column()
  declare capacity: number
  @column()
  declare cityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare time: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EventSchema extends BaseModel {
  static $columns = ['createdAt', 'date', 'description', 'id', 'isRecurring', 'location', 'title', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRecurring: boolean | null
  @column()
  declare location: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LieuxSchema extends BaseModel {
  static $columns = ['address', 'color', 'createdAt', 'id', 'name', 'notes', 'type', 'updatedAt'] as const
  $columns = LieuxSchema.$columns
  @column()
  declare address: string
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'imageUrl', 'name', 'price', 'stockPerDate', 'unit', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare stockPerDate: number | null
  @column()
  declare unit: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class ReservationItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'qty', 'reservationId', 'unitPrice', 'updatedAt'] as const
  $columns = ReservationItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number | null
  @column()
  declare qty: number
  @column()
  declare reservationId: number | null
  @column()
  declare unitPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReservationSchema extends BaseModel {
  static $columns = ['createdAt', 'distributionDateId', 'id', 'status', 'total', 'updatedAt', 'userId'] as const
  $columns = ReservationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare distributionDateId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class SellingPlaceSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'id', 'name', 'schedule', 'updatedAt'] as const
  $columns = SellingPlaceSchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare schedule: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'facebookUrl', 'id', 'instagramUrl', 'phones', 'updatedAt'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare facebookUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instagramUrl: string | null
  @column()
  declare phones: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SubscriberCitySchema extends BaseModel {
  static $columns = ['cityId', 'createdAt', 'id', 'subscriberId', 'updatedAt'] as const
  $columns = SubscriberCitySchema.$columns
  @column()
  declare cityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subscriberId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SubscriberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'phone', 'updatedAt'] as const
  $columns = SubscriberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
